### PR TITLE
Update to Zig master

### PR DESCRIPTION
**Pull request by jakubvf**
Hi Jamie,

I wanted to ask whether you are still interested in maintaining this editor. Based on the commit history, it seems that you are not actively using it, but since it is not archived, I am hopeful that you may still be interested.

Changes:
1. Update the project to use nix flakes
This change helps people stay in-sync with the correct Zig version to build.
- Open a development shell in project root: 
```
$ nix develop
```
 (`$ nix-shell` should also work but I haven't tried that). This downloads Zig version specified in `flake.nix` and adds required development libraries into the environment.
- Update to latest Zig build:
```
$ nix flake update
```
This modifies `flake.lock` (Nix package-lock.json equivalent).
2. Update to [Zig v0.11 build API](https://devlog.hexops.com/2023/zig-0-11-breaking-build-changes/)
3. Catch up with other Zig changes and Mach API
4. Removed aarch64 build
I plan to add it back later.

PS: I really like your code - I find it readable + the occasional comment here and there is also nice 😀

### CODE REVIEW

**Comment by jakubvf** [comment]
Welp, I got it running.

Screenshot from 2023-03-26 12-30-58

**Comment by jamii** [comment]
I still use it, I've just been putting off upgrading everything until I have time to figure out why upgrading causes that bug :D 

This is awesome though. Maybe I should try debugging this week.

**Comment by jakubvf** [comment]
I opened it up in gdb and as far as I can tell, the vertex positions passed to OpenGL are correct.
I'm a little confused as to where the issue is stemming from. Although, if you look closely enough, it really does render the letters "focus", it's just that one of the last vertices gets put to [0, 0].

Furthermore, it responds to keystrokes and other events, which leads me to suspect that there could be an issue with the stack. Can't be sure though.

**Comment by jamii** [comment]
The bug was a change to alignment/padding of `[2]Tri(u32)` so I just replaced it with slices. 

XDG makes me sad so I stripped that out and replaced it with a manual build option.

Otherwise looks good. Thanks for the help :)

**Pull request merged**
